version: "3.8"

services:
    ganache:
        image: trufflesuite/ganache-cli
        ports:
            - "${GANACHE_PORT}:${GANACHE_PORT}"
        command: ganache-cli -h 0.0.0.0 -p ${GANACHE_PORT} --chainId ${GANACHE_CHAINID} --networkId ${GANACHE_NETWORKID}

    app:
        build: smart-contract
        depends_on:
            - ganache
        volumes:
            - .smart-contract:/app
        command: ["truffle", "migrate", "--network", "testnet"]

    couchdb:
        image: couchdb:latest
        container_name: couchdb
        ports:
            - "5984:5984"
        volumes:
            - couchdb_data:/opt/couchdb/data
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

volumes:
    couchdb_data:
        driver: local
