version: "3.8"

services:
    ganache:
        image: trufflesuite/ganache-cli
        container_name: ganache
        ports:
            - "${GANACHE_PORT}:${GANACHE_PORT}"
        command: ganache-cli -h 0.0.0.0 -p ${GANACHE_PORT} --chainId ${GANACHE_CHAINID} --networkId ${GANACHE_NETWORKID}
        volumes:
            - ganache_data:/data

    truffle:
        build: ./smart-contract
        container_name: truffle
        depends_on:
            - ganache
        volumes:
            - smart-contract-build:/app/build
        command: ["truffle", "migrate", "--network", "testnet"]

    client:
        build: ./client
        container_name: client
        depends_on:
            - truffle
        volumes:
            - smart-contract-build:/smart-contract/build
        ports:
            - "3000:3030"

    api:
        build: ./api-microservice
        container_name: api
        ports:
            - "4000:4000"

    couchdb:
        image: couchdb:latest
        container_name: couchdb
        ports:
            - "5984:5984"
        volumes:
            - couchdb_data:/opt/couchdb/data
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        networks:
            - mynetwork

    server:
        build: ./server
        container_name: server
        ports:
            - "8080:8080"
        depends_on:
            - couchdb
        networks:
            - mynetwork

volumes:
    smart-contract-build:
    ganache_data:
    couchdb_data:
        driver: local

networks:
    mynetwork:
        driver: bridge
