root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  include = []
  follow_symlink = false
  delay = 1000

[log]
  time = true
  level = "debug"

[color]
  main = "cyan"
  watcher = "blue"
  build = "yellow"
  runner = "green"
